import intf_libs += libcrails%lib{crails}
import intf_libs += libcrails-random%lib{crails-random}

lib{crails-multipart-parser}: {hxx ixx txx cxx}{**} $impl_libs $intf_libs

hxx{export}@./: cxx.importable = false

cxx.poptions =+  "-I$out_root" "-I$src_root"

{hbmia obja}{*}: cxx.poptions += -DLIBCRAILS_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DLIBCRAILS_SHARED_BUILD

lib{crails-multipart-parser}:
{
  cxx.export.poptions = "-I$out_root/libcrails-multipart-parser/" "-I$src_root/libcrails-multipart-parser/"
  cxx.export.libs = $intf_libs
}

liba{crails-multipart-parser}: cxx.export.poptions += -DLIBCRAILS_STATIC
libs{crails-multipart-parser}: cxx.export.poptions += -DLIBCRAILS_SHARED

if $version.pre_release
  lib{crails-multipart-parser}: bin.lib.version = "-$version.project_id"
else
  lib{crails-multipart-parser}: bin.lib.version = "-$version.major.$version.minor"

{hxx ixx txx}{*}:
{
  install         = include/
  install.subdirs = true
}
